name: nestjs-template

services:
  db:
    image: postgres:15-alpine
    container_name: nestjs-template-compose-db
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - POSTGRES_DB=${PGDATABASE}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      database:
        ipv4_address: 172.20.0.6

  backend:
    build:
      context: .
      args:
        - DATABASE_URL=postgresql://${PGUSER}:${PGPASSWORD}@nestjs-template-compose-db:5432/${PGDATABASE}?schema=public&connect_timeout=300
        - DIRECT_DATABASE_URL=postgresql://${PGUSER}:${PGPASSWORD}@nestjs-template-compose-db:5432/${PGDATABASE}?schema=public&connect_timeout=300
    container_name: nestjs-template-backend
    restart: unless-stopped
    ports:
      - "${PORT:-4242}:4242"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - PGDATABASE=${PGDATABASE}
      - PGUSER=${PGUSER}
      - PGPASSWORD=${PGPASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - APP_HOST=${APP_HOST}
    networks:
      database:
        ipv4_address: 172.20.0.5

volumes:
  db_data:

networks:
  # Database  172.20.0.4/30 - 172.20.0.7/30
  database:
    ipam:
      config:
        - subnet: "172.20.0.0/16"
          gateway: "172.20.0.1"
          ip_range: "172.20.0.4/30"