services:
  db:
    image: postgres:15-alpine
    container_name: nestjs-template-compose-db
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - POSTGRES_DB=${PGDATABASE}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      database:

  backend:
    build: .
    container_name: nestjs-template-backend
    restart: unless-stopped
    ports:
      - "4242:4242"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - PGDATABASE=${PGDATABASE}
      - PGUSER=${PGUSER}
      - PGPASSWORD=${PGPASSWORD}
      - DATABASE_URL=postgresql://${PGUSER}:${PGPASSWORD}@nestjs-template-compose-db:5432/${PGDATABASE}?schema=public&connect_timeout=300
      - DIRECT_DATABASE_URL=postgresql://${PGUSER}:${PGPASSWORD}@nestjs-template-compose-db:5432/${PGDATABASE}?schema=public&connect_timeout=300
      - JWT_SECRET=${JWT_SECRET}
      - APP_HOST=${APP_HOST}
    networks:
      database:

volumes:
  db_data:

networks:
  database: