#!/usr/bin/env sh

#
# This script is CRUCIAL, because Prisma can not find
# engine file if we will not copy it to dist folder manually.
#

echo "🗂️ Starting linking Prisma engines"

DEST="./dist"
SEARCH_PATH="./node_modules/@prisma/engines"
PATTERN="libquery*"

# Ensure that engines will be found in search folder
if [[ "$(find $SEARCH_PATH -type f -name "$PATTERN")" == "" ]]; then
  echo "🛑 Did not found any engines"
  exit 1
fi

find $SEARCH_PATH -type f -name "$PATTERN" | while IFS= read -r engine; do
  name=$(basename $engine)
  cp $engine $DEST/$name
  echo "📂 Copied:"
  echo "- From:  $engine"
  echo "- To:    $DEST/$name"
done
